import { getServiceClient } from './access';

// ─── QUERIES (company-scoped) ─────────────────────────────────────────

/**
 * Get all investors for a company.
 */
export async function getInvestorsByCompany(companyId: string) {
  const supabase = getServiceClient();

  const { data, error } = await supabase
    .from('investors')
    .select('*, sponsors (id, name, company)')
    .eq('company_id', companyId)
    .order('created_at', { ascending: false });

  if (error) throw error;
  return data || [];
}

/**
 * Get investor summary stats for a company.
 */
export async function getInvestorSummary(companyId: string) {
  const investors = await getInvestorsByCompany(companyId);

  const active = investors.filter(i => i.status === 'Active').length;
  const onboarding = investors.filter(i => i.status === 'Onboarding').length;
  const pending = investors.filter(i => i.status === 'Pending').length;
  const totalInvested = investors.reduce(
    (sum, i) => sum + Number(i.total_invested || 0), 0
  );

  return {
    total: investors.length,
    active,
    onboarding,
    pending,
    totalInvested,
  };
}

/**
 * Create a new investor for a company.
 */
export async function createInvestor(
  companyId: string,
  data: {
    full_name: string;
    email: string;
    phone?: string;
    status?: string;
    sponsor_id?: string;
    initial_investment?: number;
    notes?: string;
    tags?: string[];
  }
) {
  const supabase = getServiceClient();

  const { data: investor, error } = await supabase
    .from('investors')
    .insert({
      company_id: companyId,
      investor_id: '', // auto-generated by trigger
      ...data,
      status: data.status || 'Onboarding',
    })
    .select()
    .single();

  if (error) throw error;
  return investor;
}
